name = "stm32l0xx_ll"
description = "Low-level drivers for STMicroelectronics' STM32L0 MCU series"
version = "0.7.4-dev"

authors = ["Emanuele Zarfati"]
maintainers = ["Emanuele Zarfati <zarfati.tecno@gmail.com>"]
maintainers-logins = ["ezetec"]

[[depends-on]]
gnat_arm_elf = "^13.2.1"
stm32l0xx_cmsis = "1.0.0"

[[pins]]

[pins.stm32l0xx_cmsis]
url = 'https://gitlab.com/itafraze/alire-crate-stm32l0xx-cmsis.git'
branch = 'develop'

[build-profiles]
stm32l0xx_cmsis = "release"

[build-switches]
"*".ada_version = ["-gnatX0"]

[build-switches.release]
optimization    = "size"       # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info      = "no"         #
runtime_checks  = "none"       # "-gnatp"
compile_checks  = "none"       #
contracts       = "no"         #
style_checks    = "yes"        # "-gnaty3", "-gnatya", "-gnatyA", "-gnatyB", "-gnatyb", "-gnatyc", "-gnaty-d", "-gnatye", "-gnatyf", "-gnatyh", "-gnatyi", "-gnatyI", "-gnatyk", "-gnatyl", "-gnatym", "-gnatyn", "-gnatyO", "-gnatyp", "-gnatyr", "-gnatyS", "-gnatyt", "-gnatyu", "-gnatyx"

[build-switches.validation]
optimization    = "size"       # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info      = "no"         #
runtime_checks  = "everything" # "-gnato"
compile_checks  = "errors"     # "-gnatwa", "-gnatw.X", "-gnatVa", "-gnatwe"
contracts       = "yes"        # "-gnata"
style_checks    = "yes"        # "-gnaty3", "-gnatya", "-gnatyA", "-gnatyB", "-gnatyb", "-gnatyc", "-gnaty-d", "-gnatye", "-gnatyf", "-gnatyh", "-gnatyi", "-gnatyI", "-gnatyk", "-gnatyl", "-gnatym", "-gnatyn", "-gnatyO", "-gnatyp", "-gnatyr", "-gnatyS", "-gnatyt", "-gnatyu", "-gnatyx"

[build-switches.development]
optimization    = "debug"      # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info      = "yes"        # "-g"
runtime_checks  = "default"    #
compile_checks  = "warnings"   # "-gnatwa", "-gnatw.X", "-gnatVa"
contracts       = "yes"        # "-gnata"
style_checks    = "no"         #

[configuration.variables]
Disable_Restrictions = {type = "Boolean", default = false}
LSI_Frequency = {type = "Integer", default = 37_000}
HSI_Frequency = {type = "Integer", default = 16_000_000}
HSI48_Frequency = {type = "Integer", default = 48_000_000}
LSE_Frequency = {type = "Integer", default = 32_768}
HSE_Frequency = {type = "Integer", default = 8_000_000}
