= Alire Crate - STM32L0xx LL
Emanuele Zarfati <zarfati.tecno@gmail.com>
:copyright: Copyright (C) 2024 Emanuele Zarfati. All rights reserved.
:toc: preamble
:toclevels: 2
:hide-uri-scheme:

This repository provides the low-layer drivers library for the
STMicroelectronics
link:https://www.st.com/en/microcontrollers-microprocessors/stm32l0-series.html[STM32L0]
MCU series and is intended to be distributed via the
link:https://alire.ada.dev/[Alire] package manager. This library, ported from
C to Ada, is based on the following projects:

.Credits
[cols="3,^1",width=75%,frame=none,grid=rows,role=center]
|===
| Project | Version

| STMicroelectronics's STM32CubeL0 HAL Driver MCU Component |
link:https://github.com/STMicroelectronics/stm32l0xx_hal_driver/tree/v1.10.6[v1.10.6]

|===

== Repository structure

.Content
[cols="1,3",width=75%,frame=none,grid=rows,role=center]
|===
|Path|Description

|link:./src/[`src/`] | Library source files

|link:./tests/[`tests/`] | Library test subproject

|link:./tests/[`share/`] | Utilities shared with Alire projects using this one

|===

== Support status

Development of this library has started to support the STM32L011D4 MCU.
Despite efforts to port the entire STMicroelectronics cmsis_device_l0 project
from C to Ada, support for the entire family cannot yet be guaranteed due to
lack of testing.

.Supported drivers
[cols="1,^1,4",width=75%,frame=none,grid=rows,role=center]
|===
| Driver | Status | Details

| ADC | ∂ |
| BUS | ∂ |
| COMP | |
| CORTEX | |
| CRC | |
| CRS | |
| DAC | |
| DMA | |
| EXTI | |
| GPIO | ∂ |
| I2C | |
| IWDG | |
| LPTIM | ∂ | No get functions, no encoder mode
| LPUART | |
| PWR | ∂ |
| RCC | ∂ | No: HSE CSS, HSI Output, HSI48, USB, full driver (USART, I2C,
LPUART, USB)
| RNG | |
| RTC | |
| SPI | |
| SYSTEM | |
| TIM | ∂ |
| USART | |
| UTILS | |
| WWDG | |

|===

== Development

=== Requests and reporting

Please report bugs or feature requests to the project maintainers, preferably
using the
link:https://gitlab.com/ezetec-alire-crates/stm32l0xx-ll/-/issues[issues
tracker].

=== Workflow

The main development takes place on the `develop` branch. Small,
self-contained updates can be committed directly to the `develop` branch,
while more impacting one should have dedicated `feature` branches.


=== Alire aliases

Alire aliases can be configured to simplify frequent toolchain operations,
especially if involving the `.gpr` project file or environment variables
provided by Alire. Script file link:make-aliases.sh[make-aliases.sh] is
provided to configure the following aliases:

* `alr emu`: (tests subproject) Execute tests in emulated environment.

This alias uses GNATemu, hence it requires `arm-eabi-gnatemu` to be available
in `$PATH`. At the time of writing, it is not available through Alire. However
non-GNATPro users may still find available ARM ELF GNAT Community Edition,
which ships also the `arm-eabi-gnatemu` binary, at AdaCore's
link:https://www.adacore.com/download[Download page].

=== Tests on emulated target

The target platform can be emulated using GNATemu. Sub-crate project
link:./tests/tests.gpr[`tests/tests.gpr`] supplies the `Emulator` package with
minimal working configuration. To run `tests` in the emulated environment,
execute from within the sub-project folder the following command.

.Start tests in emulation environment
[source,console]
----
$ alr emu
----

== License

Licensed under the link:http://www.apache.org/licenses/LICENSE-2.0[Apache
License, Version 2.0].

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
